#pragma once

#include "StringRef.h"

static const StringRef methods_str[] = {
    TO_STRINGREF("HTTP_INVALID"),
    TO_STRINGREF("GET"),
    TO_STRINGREF("HEAD"),
    TO_STRINGREF("POST"),
    TO_STRINGREF("PUT"),
    TO_STRINGREF("DELETE"),
    TO_STRINGREF("OPTIONS"),
    TO_STRINGREF("CONNECT"),
    TO_STRINGREF("TRACE"),
    TO_STRINGREF("PATCH"),
};

static const StringRef versions_str[] = {
    TO_STRINGREF("undefined"),
    TO_STRINGREF("HTTP/0.9"),
    TO_STRINGREF("HTTP/1.0"),
    TO_STRINGREF("HTTP/1.1"),
    TO_STRINGREF("HTTP/2"),
    TO_STRINGREF("HTTP/3"),
};

// Beautifully compile-time evaluated lookup tables for header options
static const StringRef header_request_options_str[] = {
    TO_STRINGREF("A-IM"),
    TO_STRINGREF("Accept"),
    TO_STRINGREF("Accept-Charset"),
    TO_STRINGREF("Accept-Datetime"),
    TO_STRINGREF("Accept-Encoding"),
    TO_STRINGREF("Accept-Language"),
    TO_STRINGREF("Access-Control-Request-Method"),
    TO_STRINGREF("Access-Control-Request-Headers"),
    TO_STRINGREF("Authorization"),
    TO_STRINGREF("Cache-Control"),
    TO_STRINGREF("Connection"),
    TO_STRINGREF("Content-Encoding"),
    TO_STRINGREF("Content-Length"),
    TO_STRINGREF("Content-MD5"),
    TO_STRINGREF("Content-Type"),
    TO_STRINGREF("Cookie"),
    TO_STRINGREF("Date"),
    TO_STRINGREF("Expect"),
    TO_STRINGREF("Forwarded"),
    TO_STRINGREF("From"),
    TO_STRINGREF("Host"),
    TO_STRINGREF("HTTP2-Settings"),
    TO_STRINGREF("If-Match"),
    TO_STRINGREF("If-Modified-Since"),
    TO_STRINGREF("If-None-Match"),
    TO_STRINGREF("If-Range"),
    TO_STRINGREF("If-Unmodified-Since"),
    TO_STRINGREF("Max-Forwards"),
    TO_STRINGREF("Origin"),
    TO_STRINGREF("Pragma"),
    TO_STRINGREF("Prefer"),
    TO_STRINGREF("Proxy-Authorization"),
    TO_STRINGREF("Range"),
    TO_STRINGREF("Referer"),
    TO_STRINGREF("TE"),
    TO_STRINGREF("Trailer"),
    TO_STRINGREF("Transfer-Encoding"),
    TO_STRINGREF("User-Agent"),
    TO_STRINGREF("Upgrade"),
    TO_STRINGREF("Via"),
    TO_STRINGREF("Warning"),
};

static const StringRef header_response_options_str[] = {
    TO_STRINGREF("Accept-CH"),
    TO_STRINGREF("Access-Control-Allow-Origin"),
    TO_STRINGREF("Access-Control-Allow-Credentials"),
    TO_STRINGREF("Access-Control-Expose-Headers"),
    TO_STRINGREF("Access-Control-Max-Age"),
    TO_STRINGREF("Access-Control-Allow-Methods"),
    TO_STRINGREF("Access-Control-Allow-Headers"),
    TO_STRINGREF("Accept-Patch"),
    TO_STRINGREF("Accept-Ranges"),
    TO_STRINGREF("Age"),
    TO_STRINGREF("Allow"),
    TO_STRINGREF("Alt-Svc"),
    TO_STRINGREF("Cache-Control"),
    TO_STRINGREF("Connection"),
    TO_STRINGREF("Content-Disposition"),
    TO_STRINGREF("Content-Encoding"),
    TO_STRINGREF("Content-Language"),
    TO_STRINGREF("Content-Length"),
    TO_STRINGREF("Content-Location"),
    TO_STRINGREF("Content-MD5"),
    TO_STRINGREF("Content-Range"),
    TO_STRINGREF("Content-Type"),
    TO_STRINGREF("Date"),
    TO_STRINGREF("Delta-Base"),
    TO_STRINGREF("ETag"),
    TO_STRINGREF("Expires"),
    TO_STRINGREF("IM"),
    TO_STRINGREF("Last-Modified"),
    TO_STRINGREF("Link"),
    TO_STRINGREF("Location"),
    TO_STRINGREF("P3P"),
    TO_STRINGREF("Pragma"),
    TO_STRINGREF("Preference-Applied"),
    TO_STRINGREF("Proxy-Authenticate"),
    TO_STRINGREF("Public-Key-Pins"),
    TO_STRINGREF("Retry-After"),
    TO_STRINGREF("Server"),
    TO_STRINGREF("Set-Cookie"),
    TO_STRINGREF("Strict-Transport-Security"),
    TO_STRINGREF("Trailer"),
    TO_STRINGREF("Transfer-Encoding"),
    TO_STRINGREF("Tk"),
    TO_STRINGREF("Upgrade"),
    TO_STRINGREF("Vary"),
    TO_STRINGREF("Via"),
    TO_STRINGREF("Warning"),
    TO_STRINGREF("WWW-Authenticate"),
    TO_STRINGREF("X-Frame-Options"),
    TO_STRINGREF("Status"),
};

// keeping this for consistency with the other strings
// but this should not be used
static const StringRef reason_phrases_str[] = {
    TO_STRINGREF("Continue"),
    TO_STRINGREF("Switching Protocols"),
    TO_STRINGREF("OK"),
    TO_STRINGREF("Created"),
    TO_STRINGREF("Accepted"),
    TO_STRINGREF("Non-Authoritative Information"),
    TO_STRINGREF("No Content"),
    TO_STRINGREF("Reset Content"),
    TO_STRINGREF("Partial Content"),
    TO_STRINGREF("Multiple Choices"),
    TO_STRINGREF("Moved Permanently"),
    TO_STRINGREF("Found"),
    TO_STRINGREF("See Other"),
    TO_STRINGREF("Not Modified"),
    TO_STRINGREF("Use Proxy"),
    TO_STRINGREF("Temporary Redirect"),
    TO_STRINGREF("Bad Request"),
    TO_STRINGREF("Unauthorized"),
    TO_STRINGREF("Payment Required"),
    TO_STRINGREF("Forbidden"),
    TO_STRINGREF("Not Found"),
    TO_STRINGREF("Method Not Allowed"),
    TO_STRINGREF("Not Acceptable"),
    TO_STRINGREF("Proxy Authentication Required"),
    TO_STRINGREF("Request Time-out"),
    TO_STRINGREF("Conflict"),
    TO_STRINGREF("Gone"),
    TO_STRINGREF("Length Required"),
    TO_STRINGREF("Precondition Failed"),
    TO_STRINGREF("Request Entity Too Large"),
    TO_STRINGREF("Request-URI Too Large"),
    TO_STRINGREF("Unsupported Media Type"),
    TO_STRINGREF("Requested range not satisfiable"),
    TO_STRINGREF("Expectation Failed"),
    TO_STRINGREF("Internal Server Error"),
    TO_STRINGREF("Not Implemented"),
    TO_STRINGREF("Bad Gateway"),
    TO_STRINGREF("Service Unavailable"),
    TO_STRINGREF("Gateway Time-out"),
    TO_STRINGREF("HTTP Version not supported")};

constexpr unsigned char server_version_major = 4;
constexpr unsigned char server_version_minor = 0;
