#include "methods.h"

#define ADD_CAST_MAP MiniMap_StringRef_StringRef_set(mimeTypes, &k, &v, equal_StringRef)

void setup_content_types(MiniMap_StringRef_StringRef *mimeTypes) {

	StringRef k = {};
	StringRef v = {};

	k = CAST_STRINGREF("abw");
	v = CAST_STRINGREF("application/x-abiword");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("aac");
	v = CAST_STRINGREF("audio/aac");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("arc");
	v = CAST_STRINGREF("application/x-freearc");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("avif");
	v = CAST_STRINGREF("image/avif");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("aac");
	v = CAST_STRINGREF("audio/aac");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("avi");
	v = CAST_STRINGREF("video/x-msvideo");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("azw");
	v = CAST_STRINGREF("application/vnd.amazon.ebook");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("bin");
	v = CAST_STRINGREF("application/octet-stream");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("bmp");
	v = CAST_STRINGREF("image/bmp");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("bz");
	v = CAST_STRINGREF("application/x-bzip");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("bz2");
	v = CAST_STRINGREF("application/x-bzip2");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("cda");
	v = CAST_STRINGREF("application/x-cdf");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("csh");
	v = CAST_STRINGREF("application/x-csh");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("css");
	v = CAST_STRINGREF("text/css");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("csv");
	v = CAST_STRINGREF("text/csv");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("doc");
	v = CAST_STRINGREF("application/msword");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("docx");
	v = CAST_STRINGREF("application/vnd.openxmlformats-officedocument.wordprocessingml.document");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("eot");
	v = CAST_STRINGREF("application/vnd.ms-fontobject");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("exe");
	v = CAST_STRINGREF("application/octet-stream");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("epub");
	v = CAST_STRINGREF("application/epub+zip");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("gz");
	v = CAST_STRINGREF("application/gzip");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("gif");
	v = CAST_STRINGREF("image/gif");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("tml");
	v = CAST_STRINGREF("text/html");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("htm");
	v = CAST_STRINGREF("text/html");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("html");
	v = CAST_STRINGREF("text/html");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("ico");
	v = CAST_STRINGREF("image/vnd.microsoft.icon");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("ics");
	v = CAST_STRINGREF("text/calendar");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("jar");
	v = CAST_STRINGREF("application/java-archive");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("jpeg");
	v = CAST_STRINGREF("image/jpeg");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("jpg");
	v = CAST_STRINGREF("image/jpeg");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("js");
	v = CAST_STRINGREF("text/javascript");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("json");
	v = CAST_STRINGREF("application/json");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("jsonld");
	v = CAST_STRINGREF("application/ld+json");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("midi");
	v = CAST_STRINGREF("audio/midi");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("mid");
	v = CAST_STRINGREF("audio/midi");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("mjs");
	v = CAST_STRINGREF("text/javascript");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("mp3");
	v = CAST_STRINGREF("audio/mpeg");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("mp4");
	v = CAST_STRINGREF("video/mp4");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("mpeg");
	v = CAST_STRINGREF("video/mpeg");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("mpkg");
	v = CAST_STRINGREF("application/vnd.apple.installer+xml");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("odp");
	v = CAST_STRINGREF("application/vnd.oasis.opendocument.presentation");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("ods");
	v = CAST_STRINGREF("application/vnd.oasis.opendocument.spreadsheet");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("odt");
	v = CAST_STRINGREF("application/vnd.oasis.opendocument.text");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("oga");
	v = CAST_STRINGREF("audio/ogg");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("ogv");
	v = CAST_STRINGREF("video/ogg");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("ogx");
	v = CAST_STRINGREF("application/ogg");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("opus");
	v = CAST_STRINGREF("audio/opus");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("otf");
	v = CAST_STRINGREF("font/otf");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("png");
	v = CAST_STRINGREF("image/png");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("pdf");
	v = CAST_STRINGREF("application/pdf");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("php");
	v = CAST_STRINGREF("application/x-httpd-php");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("ppt");
	v = CAST_STRINGREF("application/vnd.ms-powerpoint");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("pptx");
	v = CAST_STRINGREF("application/vnd.openxmlformats-officedocument.presentationml.presentation");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("rar");
	v = CAST_STRINGREF("application/vnd.rar");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("rtf");
	v = CAST_STRINGREF("application/rtf");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("sh");
	v = CAST_STRINGREF("application/x-sh");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("svg");
	v = CAST_STRINGREF("image/svg+xml");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("swf");
	v = CAST_STRINGREF("application/x-shockwave-flash");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("tar");
	v = CAST_STRINGREF("application/x-tar");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("tiff");
	v = CAST_STRINGREF("image/tiff");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("tif");
	v = CAST_STRINGREF("image/tiff");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("ts");
	v = CAST_STRINGREF("video/mp2t");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("ttf");
	v = CAST_STRINGREF("font/ttf");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("txt");
	v = CAST_STRINGREF("text/plain");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("vsd");
	v = CAST_STRINGREF("application/vnd.visio");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("wav");
	v = CAST_STRINGREF("audio/wav");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("weba");
	v = CAST_STRINGREF("audio/webm");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("webm");
	v = CAST_STRINGREF("video/webm");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("webp");
	v = CAST_STRINGREF("image/webp");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("woff");
	v = CAST_STRINGREF("font/woff");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("woff2");
	v = CAST_STRINGREF("font/woff2");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("xhtml");
	v = CAST_STRINGREF("application/xhtml+xml");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("xls");
	v = CAST_STRINGREF("application/vnd.ms-excel");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("xlsx");
	v = CAST_STRINGREF("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("xml");
	v = CAST_STRINGREF("application/xml");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("xul");
	v = CAST_STRINGREF("application/vnd.mozilla.xul+xml");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("zip");
	v = CAST_STRINGREF("application/zip");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("3gp");
	v = CAST_STRINGREF("video/3gpp");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("3g2");
	v = CAST_STRINGREF("video/3gpp2");
	ADD_CAST_MAP;
	k = CAST_STRINGREF("7z");
	v = CAST_STRINGREF("application/x-7z-compressed");
	ADD_CAST_MAP;
}
